# Generated by Django 4.0.3 on 2022-04-10 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinLengthValidator(5)]),
        ),
    ]
