# Generated by Django 4.0.3 on 2022-04-10 18:30

from django.db import migrations, models
import project.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='', validators=[project.common.validators.validate_image]),
        ),
    ]
