# Generated by Django 4.0.3 on 2022-04-05 20:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=70,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ["Sofia", "Sofia"],
                            ["Plovdiv", "Plovdiv"],
                            ["Varna", "Varna"],
                            ["Burgas", "Burgas"],
                            ["Ruse", "Ruse"],
                            ["Pleven", "Pleven"],
                            ["Sliven", "Sliven"],
                            ["Dobrich", "Dobrich"],
                            ["SHumen", "SHumen"],
                            ["PERNIK", "PERNIK"],
                            ["Yambol", "Yambol"],
                        ],
                        max_length=7,
                    ),
                ),
                ("description", models.TextField(max_length=255)),
                (
                    "ppl_number",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "room_number",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                ("has_wc", models.BooleanField(default=False)),
                ("has_net", models.BooleanField(default=False)),
                ("has_kitchen", models.BooleanField(default=False)),
                ("has_tv", models.BooleanField(default=False)),
                ("has_garage", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=70,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("description", models.TextField(max_length=255)),
                (
                    "money",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                ("is_total", models.BooleanField(default=True)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ["Sofia", "Sofia"],
                            ["Plovdiv", "Plovdiv"],
                            ["Varna", "Varna"],
                            ["Burgas", "Burgas"],
                            ["Ruse", "Ruse"],
                            ["Pleven", "Pleven"],
                            ["Sliven", "Sliven"],
                            ["Dobrich", "Dobrich"],
                            ["SHumen", "SHumen"],
                            ["PERNIK", "PERNIK"],
                            ["Yambol", "Yambol"],
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
