# Generated by Django 4.0.3 on 2022-04-10 08:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0006_rename_is_total_job_compensation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="money",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(10000)]
            ),
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("food", models.BooleanField()),
                ("blankets", models.BooleanField()),
                ("cloths", models.BooleanField()),
                ("home", models.BooleanField()),
                ("toys", models.BooleanField()),
                ("money", models.BooleanField()),
                ("electric_appliances", models.BooleanField()),
                ("transportation", models.BooleanField()),
                ("phone", models.BooleanField()),
                ("pills", models.BooleanField()),
                ("others", models.BooleanField()),
                ("description", models.TextField(max_length=512)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=70)),
                ("description", models.TextField(max_length=512)),
                ("when", models.CharField(max_length=70)),
                ("where", models.CharField(max_length=70)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
