# Generated by Django 4.0.3 on 2022-04-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_job_money_questionnaire_campaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="description",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
