# Generated by Django 4.0.3 on 2022-04-10 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_campaign_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='picture',
            field=models.CharField(choices=[['/static/images/toy.png', '/static/images/toy.png']], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='ppl_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='room_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinLengthValidator(1)]),
        ),
    ]
