# Generated by Django 4.0.3 on 2022-04-11 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_campaign_picture_alter_shelter_ppl_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='ppl_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='room_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
