# Generated by Django 4.0.3 on 2022-04-12 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_shelter_ppl_number_alter_shelter_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='money',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
